image: debian:bookworm-slim

check:
  only:
    - branches@World/OpenPaperwork/libpillowfight
    - tags@World/OpenPaperwork/libpillowfight
  script:
    - apt-get update
    - apt-get install -y -q make
    - apt-get install -y -q pycodestyle flake8 python3-flake8
    - make check

test:
  only:
    - branches@World/OpenPaperwork/libpillowfight
    - tags@World/OpenPaperwork/libpillowfight
  script:
    - apt-get update
    - apt-get install -y -q
        build-essential
        gcc
        libjpeg-dev
        make
        python3-dev
        python3-pip
        python3-virtualenv
        zlib1g-dev
    - virtualenv /tmp/venv
    - source /tmp/venv/bin/activate
    - pip install pytest
    - make install_py
    - make test
