image: debian:stable-slim

check:
  tags:
    - linux
    - volatile
  script:
    - apt-get update
    - apt-get install -y -q make
    - apt-get install -y -q pycodestyle flake8 python3-flake8 tox
    - make check

test:
  tags:
    - linux
    - volatile
  script:
    - apt-get update
    - apt-get install -y -q make
    - apt-get install -y -q python3-pil build-essential gcc tox
    - make test
