#!/bin/bash

cd tests/data
gm compare black_border_problem.png black_border_problem_blackfilter.png -file black_border_problem_blackfilter_diff.png
gm compare black_border_problem.png black_border_problem_blurfilter.png -file black_border_problem_blurfilter_diff.png
gm compare black_border_problem3.png black_border_problem3_border.png -file black_border_problem3_border_diff.png
gm compare black_border_problem.png black_border_problem_grayfilter.png -file black_border_problem_grayfilter_diff.png
gm compare black_border_problem2.png black_border_problem2_masks.png -file black_border_problem2_masks_diff.png
gm compare black_border_problem.png black_border_problem_noisefilter.png -file black_border_problem_noisefilter_diff.png
